/**{# JomEntry class skeleton #}
 * {{ clazz }}  class file
 * Generated on {% now 'DATETIME_FORMAT' %}
 * 
 * Please do not edit this file as it will be overridden.
 */
{{ clazz }} = function(config) {
	
	/* Fields */
	this.fields = new Array();{% for field in fields %}
	this.fields['{{ field.name }}'] = {{ field.defaultValue }};{% endfor %}
	
	init = function(config) {
		for(var key in config) {
            this.fields[key] = config[key];
        }
	};
	init(config);
};

{% for field in fields %}
/* Get {{ field.name }} */
{{ clazz }}.prototype.get_{{ field.name }} = function() {
	return this.fields['{{ field.name }}'];
};

/* Set {{ field.name }} */
{{ clazz }}.prototype.set_{{ field.name }} = function(value) {
	this.fields['{{ field.name }}'] = value;
};
{% endfor %}



{% if include %}
	{% include include %}
{% endif %}