{# JomEntry class skeleton #}
/**
 * JomEntry class file
 * Generated on {% now DATETIME_FORMAT %}
 * 
 * Please do not edit this file as it will be overridden.
 */
{{ jom.clazz }} = function(config) {
	{% for field in jom.fields %}
		this.{{ field.name }} = {{ field.defaultValue }};
	{% endfor %}
	
	init = function(config) {
		{% for field in jom.fields %}
			this.{{ field.name }} = config[{{ field.name }}];
		{% endfor %}
	};
	init(config);
};

// Getters and setters
{% for field in jom.fields %}
	{{ jom.clazz }}.prototype.get_{{ field.name }} = function() {
		return this.{{ field.name }};
	};
	
	{{ jom.clazz }}.prototype.set_{{ field.name }} = function(value) {
		this.{{ field.name }} = value;
	};
{% endfor %}

{% if jom.include %}
	{% include jom.include %}
{% endif %}