/**{# JomEntry class skeleton #}
 * {{ clazz }}  class file
 * Generated on {% now 'DATETIME_FORMAT' %}
 * 
 * Please do not edit this file as it will be overridden.
 */
{{ clazz }} = function(config) {
	/* Fields */{% for field in fields %}
		this.{{ field.name }} = {{ field.defaultValue }};{% endfor %}
	
	init = function(config) {
		{% for field in fields %}
			this.{{ field.name }} = config[{{ field.name }}];{% endfor %}
	};
	init(config);
};

{% for field in fields %}
/* Get {{ field.name }} */
{{ clazz }}.prototype.get_{{ field.name }} = function() {
	return this.{{ field.name }};
};
/* Set {{ field.name }} */
{{ clazz }}.prototype.set_{{ field.name }} = function(value) {
	this.{{ field.name }} = value;
};
{% endfor %}
{% if include %}
	{% include include %}
{% endif %}